apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
   -  name: nginx-container
      image: nginx
      env:
      - name: ENV_VARIABLE_1
        valueFrom:
          configMapKeyRef:
            name: env-cm
            key: ENV_ONE
      - name: ENV_VARIABLE_2
        valueFrom:
          configMapKeyRef:
            name: env-cm
            key: ENV_TWO

