apiVersion: apps/v1
kind: Deployment
metadata:
  name: osticket-mysql
  labels:
    app: osticket-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  template:
    metadata:
      name: mysql-po
      labels:
        app: mysql-app
    spec:
      containers:
      - name: mysql-container
        image: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: osticket-config-yaml
              key: MYSQL_DATABASE
